# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

cache: packages

apt_packages:
  - libgsl-dev
  - jags

r_packages:
  - pkgdown
  - covr
  - boral
  
after_success:
  - R CMD INSTALL .
  - Rscript -e 'pkgdown::build_site()'
  - Rscript -e 'library(covr); codecov()'

r:
  - oldrel
  - release
  - devel   
  
deploy:
  provider: pages
  cleanup: false 
  token: $GITHUB_PAT
  keep_history: true
  local_dir: docs
  on:
    branch: master
